#!/usr/bin/perl -w

# This routine tests the "compare::on_list" which attempts to
# see if a give prime (description) is on the list

#use FindBin qw($Bin);   # Where is this script stored?  Put full path into $Bin
#use lib ($Bin,"$Bin/..","$Bin/../math","$Bin/../../bin");
use lib qw (
  /var/www/html/primes/support/modules
  /var/www/html/primes/support/math
  /var/www/html/primes/support
  /var/www/html/primes/bin
);

use Getopt::Std;	# Allow for command line options
use compare;		# Adjust prime descriptions;

&getopts('e');		# call as 'compare -e expression' if you'd like
$opt_e = $opt_e;

if ($opt_e) {
  $string = shift();
  print (&compare::on_list($string) || 'undef');
} else {
  # Interactive mode
  while (1) {
    print "expression: ";
    $string = <>;
    chop $string;
    exit if ($string =~ /^[qre ]+/o);
    $string = &compare::on_list($string) || 'undef';
    print "Returns: $string\n";
  }
}
